### ISSUE TITLE
No rage refunded on HS miss.

### ISSUE THREAD

**Issue by nuiva** [albinoyoda/wow_classic_simulator#1]
I looked at the source and found that heroic strike rage cost is not dependent on hit outcome [here](https://github.com/albinoyoda/wow_classic_simulator/blob/cbba41aeed6ac311bdf94746ffed3ba722d7bb63/wow_library/source/Combat_simulator.cpp#L495). Heroic strike is supposed to refund 80% of the rage cost on miss/dodge, like Bloodthirst.

I did not run the program to confirm this.

**Comment by albinoyoda** [comment]
> I looked at the source and found that heroic strike rage cost is not dependent on hit outcome [here](https://github.com/albinoyoda/wow_classic_simulator/blob/cbba41aeed6ac311bdf94746ffed3ba722d7bb63/wow_library/source/Combat_simulator.cpp#L495). Heroic strike is supposed to refund 80% of the rage cost on miss/dodge, like Bloodthirst.
> 
> I did not run the program to confirm this.

**Comment by albinoyoda** [comment]
> > I looked at the source and found that heroic strike rage cost is not dependent on hit outcome [here](https://github.com/albinoyoda/wow_classic_simulator/blob/cbba41aeed6ac311bdf94746ffed3ba722d7bb63/wow_library/source/Combat_simulator.cpp#L495). Heroic strike is supposed to refund 80% of the rage cost on miss/dodge, like Bloodthirst.
> > I did not run the program to confirm this.
> 
> Nice catch! Thats indeed a bug. Will fix this.
> 
> Apologies for the slow reply btw, completely missed the issues tab.

Fixed behaviour in the latest patch:
Time: 31.050367s. Event: Current rage: 78
Time: 31.913393s. Event: Performing heroic strike
Time: 31.913393s. Event: Drawing outcome from yellow table
Time: 31.913393s. Event: Ability dodged
Time: 31.913393s. Event: Current rage: 76
...
Time: 32.130515s. Event: Current rage: 47
Time: 32.782969s. Event: Performing heroic strike
Time: 32.782969s. Event: Drawing outcome from yellow table
Time: 32.782969s. Event: Ability hit for: 432 damage.
Time: 32.782969s. Event: Current rage: 34

(the rage in the sim is a positive float, but when printed it is cast to an integer, so there is a floor operation applied on the printed values which is why they arent exact.)
